### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by Fabian96H** [TickTack-Zeiterfassung/TickTack-App#10]
**Soll die Anwendung mehrsprachig werden?**

- lohnt es sich die Anwendung mehrsprachig zu entwickeln?
- wie aufwendig wäre die Mehrsprachigkeit?
- sollte dies (falls ja) von vornherein immer mit implementiert werden oder kann dies auch problemlos am Ende erfolgen?
- wie könnte ein Konzept zur Umsetzung von Mehrsprachigkeit in der Ionic-Anwendung aussehen?

**Comment by matze6633** [comment]
Ist prinzipiell relativ einfach Möglich. Falls die Anwendung wirklich veröffentlicht werden sollte, wäre ich dafür die Anwendung mehrsprachig zu entwickeln.

http://ionicframework.com/docs/developer-resources/ng2-translate/

**Comment by matze6633** [comment]
Mit #46 implementiert
