### ISSUE TITLE
Implementierung der Firebase-Schnittstelle

### ISSUE THREAD

**Issue by matze6633** [TickTack-Zeiterfassung/TickTack-App#14]
Für die Datenpersitierung in der Firebase-Datenbank, muss das IDataInterface für Firebase entwickelt werden.

**Comment by matze6633** [comment]
Moegliche Datenstruktur innerhalb der Firebase-Datenbank:

```
\uid\
	user\
		email
		name
	projects\ 
		[
			id
			name
			color
		]
	times\
		[
			id
			project-id
			start-timestamp
			end-timestamp
			duration
			message
		]
```

**Comment by matze6633** [comment]
Die ID jedes Objektes sollte sich aus dem Index des Arrays ergeben, da beim Anlegen eines Items das Item selber noch keine interne ID besitzt -> ergibt sich erst beim nächsten auslesen der Daten. Ausserdem wird dadurch eine mehrfach Indizierung verhindert.

Weiterhin sollten die "Tabellen", falls sich nicht vorhanden sind, beim Einfügen eines Items erstellt werden, um Konflikte zu verhindern.

Zuletzt muss gewährleistet werden, dass bevor dem Logout eines Nutzers alle Observables abgemeldet werden müssen

**Comment by Maarcel** [comment]
Erledigt
